### ISSUE TITLE
Question to aiocoap

### ISSUE THREAD

**Issue by Cyber1000** [betaboon/aioairctrl#3]
Hi, since we are using coapthon3 for https://github.com/rgerganov/py-air-control and this pip is very old, I'm thinking of transitioning to aiocoap.
I've made aware [here](https://github.com/rgerganov/py-air-control/issues/58#issuecomment-821795360) that you are doing something similar, we have currently some problems at this point.

I've seen you are monkeypatching aiocoap, just wanted to ask, what problem you experienced here and if there is an issue in aiocoap?

Thanks!

**Comment by betaboon** [comment]
So far it has been working quite nicely.

issues that are not yet solved:
- reconnecting when the device was powerd down while the observation is running

I'm monkey patching two aspects:
- handling `asyncio.CancelledError` which otherwise causes an ugly stacktrace on `Ctrl-c`
- removing deduplication functionality: i do this as several philips models just keep sending `MID=1` on every observation-message (which to my knowledge is non spec-compliant) which effectively causes them to be ignored.

**Comment by Cyber1000** [comment]
Thanks for clarifying, have tried it out now, works without problems for me. 
Closing this question.
